const lessonTitle = "大声地生活";

const lessonData = [
    // ===== 第 1 段 =====
    ["那天", "nà tiān", "That day", "Hari itu"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["领着", "lǐng zhe", "led", "membawa"],
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["上街", "shàng jiē", "went to the street", "ke jalan"],
    ["，", "", "", ""],
    ["在", "zài", "at", "di"],
    ["一个", "yí gè", "a", "sebuah"],
    ["书摊", "shū tān", "bookstall", "gerai buku"],
    ["前", "qián", "in front of", "di hadapan"],
    ["选", "xuǎn", "selected", "memilih"],
    ["了", "le", "", ""],
    ["两本", "liǎng běn", "two", "dua buah"],
    ["书", "shū", "books", "buku"],
    ["，", "", "", ""],
    ["手", "shǒu", "hand", "tangan"],
    ["伸到", "shēn dào", "reached into", "masuk ke"],
    ["兜里", "dōu lǐ", "pocket", "dalam poket"],
    ["掏钱", "tāo qián", "took out money", "mengeluarkan wang"],
    ["，", "", "", ""],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["碰到", "pèng dào", "touched", "tersentuh"],
    ["一只手", "yì zhī shǒu", "a hand", "sebatang tangan"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["吓了一跳", "xià le yī tiào", "was startled", "terkejut"],
    ["，", "", "", ""],
    ["禁不住", "jīn bú zhù", "couldn't help", "tidak dapat menahan"],
    ["“", "", "", ""],
    ["哎", "āi", "Ah", "Aduh"],
    ["”", "", "", ""],
    ["了", "le", "", ""],
    ["一声", "yì shēng", "a sound", "sekali"],
    ["。", "", "", ""],
    ["一个", "yí gè", "A", "Seorang"],
    ["男人", "nán rén", "man", "lelaki"],
    ["嗖地", "sōu de", "quickly", "dengan pantas"],
    ["转身", "zhuǎn shēn", "turned", "berpusing"],
    ["离开了", "lí kāi le", "left", "pergi"],
    ["，", "", "", ""],
    ["留给", "liú gěi", "leaving", "meninggalkan"],
    ["我", "wǒ", "me", "saya"],
    ["一个", "yí gè", "a", "sebuah"],
    ["身穿", "shēn chuān", "wearing", "memakai"],
    ["黑色", "hēi sè", "black", "hitam"],
    ["皮夹克", "pí jiā kè", "leather jacket", "jaket kulit"],
    ["的", "de", "", ""],
    ["背影", "bèi yǐng", "back view", "bayangan belakang"],
    ["。", "", "", ""],
    ["女儿", "nǚ ér", "Daughter", "Anak perempuan"],
    ["在旁边", "zài páng biān", "beside", "di sisi"],
    ["连忙", "lián máng", "hurriedly", "segera"],
    ["问", "wèn", "asked", "bertanya"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["妈妈", "mā ma", "Mom", "Ibu"],
    ["，", "", "", ""],
    ["怎么了", "zěn me le", "what's wrong", "apa berlaku"],
    ["？”", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["小声地", "xiǎo shēng de", "quietly", "dengan perlahan"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["有", "yǒu", "There is", "Ada"],
    ["小偷", "xiǎo tōu", "thief", "pencuri"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段

    ["女儿", "nǚ ér", "Daughter", "Anak perempuan"],
    ["大声说", "dà shēng shuō", "said loudly", "berkata dengan kuat"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["在哪儿", "zài nǎ r", "Where", "Di mana"],
    ["？", "", "", ""],
    ["快", "kuài", "Quickly", "Cepat"],
    ["抓住", "zhuā zhù", "catch", "tangkap"],
    ["他", "tā", "him", "dia"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段

    ["我", "wǒ", "I", "Saya"],
    ["用", "yòng", "used", "dengan"],
    ["手指", "shǒu zhǐ", "finger", "jari"],
    ["了指", "zhǐ le", "pointed at", "menunjuk"],
    ["那个", "nà ge", "that", "itu"],
    ["背影", "bèi yǐng", "back view", "bayangan belakang"],
    ["，", "", "", ""],
    ["小声说", "xiǎo shēng shuō", "said quietly", "berkata perlahan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["就是", "jiù shì", "It's", "Itulah"],
    ["他", "tā", "him", "dia"],
    ["，", "", "", ""],
    ["不过", "bú guò", "but", "tetapi"],
    ["没偷着", "méi tōu zhe", "didn't steal anything", "tidak berjaya mencuri"],
    ["，", "", "", ""],
    ["别吱声", "bié zī shēng", "don't make a sound", "jangan bersuara"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段

    ["想不到", "xiǎng bú dào", "Unexpectedly", "Tidak disangka"],
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["冲着", "chòng zhe", "facing", "menghadap"],
    ["那个", "nà ge", "that", "itu"],
    ["背影", "bèi yǐng", "back view", "bayangan belakang"],
    ["大声地", "dà shēng de", "loudly", "dengan kuat"],
    ["喊道", "hǎn dào", "shouted", "menjerit"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["坏蛋", "huài dàn", "Rascal", "Jahat"],
    ["！", "", "", ""],
    ["小偷", "xiǎo tōu", "Thief", "Pencuri"],
    ["！", "", "", ""],
    ["谁", "shuí", "Who", "Siapa"],
    ["让你", "ràng nǐ", "let you", "benarkan awak"],
    ["偷", "tōu", "steal", "curi"],
    ["我", "wǒ", "my", "saya punya"],
    ["妈妈", "mā ma", "mom's", "ibu"],
    ["的钱", "de qián", "money", "wang"],
    ["？", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["要", "yào", "will", "akan"],
    ["告诉", "gào su", "tell", "beritahu"],
    ["警察", "jǐng chá", "police", "polis"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段

    ["我", "wǒ", "I", "Saya"],
    ["吓得", "xià de", "scared", "takut"],
    ["用", "yòng", "with", "dengan"],
    ["手", "shǒu", "hand", "tangan"],
    ["猛拉", "měng lā", "pulled hard", "tarik kuat"],
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["两下", "liǎng xià", "twice", "dua kali"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["别喊了", "bié hǎn le", "Stop shouting", "Jangan jerit"],
    ["，", "", "", ""],
    ["你爸爸", "nǐ bà ba", "your father", "ayah awak"],
    ["又", "yòu", "also", "juga"],
    ["不在这儿", "bú zài zhè r", "isn't here", "tiada di sini"],
    ["，", "", "", ""],
    ["小心", "xiǎo xīn", "be careful", "berhati-hati"],
    ["他", "tā", "he", "dia"],
    ["来", "lái", "come", "datang"],
    ["打", "dǎ", "hit", "pukul"],
    ["我们", "wǒ men", "us", "kita"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段

    ["“", "", "", ""],
    ["他敢", "tā gǎn", "He dares", "Beranikah dia"],
    ["？", "", "", ""],
    ["有", "yǒu", "There are", "Ada"],
    ["警察", "jǐng chá", "police", "polis"],
    ["呢", "ne", "particle", "!"],
    ["。", "", "", ""],
    ["妈妈", "mā ma", "Mom", "Ibu"],
    ["，", "", "", ""],
    ["快", "kuài", "Quickly", "Cepat"],
    ["把", "bǎ", "to", "untuk"],
    ["电话", "diàn huà", "phone", "telefon"],
    ["拿出来", "ná chū lái", "take out", "keluarkan"],
    ["，", "", "", ""],
    ["打", "dǎ", "call", "hubungi"],
    ["110", "yī yī líng", "110", "110"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["理直气壮地", "lǐ zhí qì zhuàng de", "confidently", "dengan yakin"],
    ["继续", "jì xù", "continued", "terus"],
    ["大声说", "dà shēng shuō", "said loudly", "berkata dengan kuat"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段

    ["我", "wǒ", "I", "Saya"],
    ["有些", "yǒu xiē", "somewhat", "agak"],
    ["害怕地", "hài pà de", "fearfully", "dengan takut"],
    ["看着", "kàn zhe", "looked at", "melihat"],
    ["那个", "nà ge", "that", "itu"],
    ["背影", "bèi yǐng", "back view", "bayangan belakang"],
    ["，", "", "", ""],
    ["生怕", "shēng pà", "afraid", "takut"],
    ["他", "tā", "he", "dia"],
    ["回转身来", "huí zhuǎn shēn lái", "turn back", "berpusing balik"],
    ["打", "dǎ", "hit", "pukul"],
    ["我们", "wǒ men", "us", "kita"],
    ["母女", "mǔ nǚ", "mother and daughter", "ibu dan anak"],
    ["。", "", "", ""],
    ["可是", "kě shì", "however", "namun"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["没有", "méi yǒu", "did not", "tidak"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["走得", "zǒu de", "walked", "berjalan"],
    ["更快了", "gèng kuài le", "faster", "lebih cepat"],
    ["，", "", "", ""],
    ["走到", "zǒu dào", "reached", "sampai ke"],
    ["街角", "jiē jiǎo", "street corner", "sudut jalan"],
    ["拐弯处", "guǎi wān chù", "turn", "selekoh"],
    ["，", "", "", ""],
    ["急忙", "jí máng", "hurriedly", "segera"],
    ["钻进", "zuān jìn", "darted into", "masuk ke"],
    ["巷子里", "xiàng zi lǐ", "alley", "lorong"],
    ["，", "", "", ""],
    ["看不见了", "kàn bú jiàn le", "disappeared", "hilang"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["这才", "zhè cái", "only then", "baru"],
    ["松口气", "sōng kǒu qì", "breathed a sigh of relief", "lega"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段

    ["这时", "zhè shí", "At this moment", "Pada masa ini"],
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["拉拉", "lā la", "pulled", "tarik"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["手", "shǒu", "hand", "tangan"],
    ["，", "", "", ""],
    ["生气地", "shēng qì de", "angrily", "dengan marah"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["妈妈", "mā ma", "Mom", "Ibu"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["为什么", "wèi shén me", "why", "kenapa"],
    ["不", "bù", "didn't", "tidak"],
    ["报警察", "bào jǐng chá", "call the police", "laporkan polis"],
    ["？", "", "", ""],
    ["你看", "nǐ kàn", "look", "lihat"],
    ["你", "nǐ", "you", "awak"],
    ["让他", "ràng tā", "let him", "biarkan dia"],
    ["跑了", "pǎo le", "got away", "lari"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["又", "yòu", "again", "lagi"],
    ["去", "qù", "go", "pergi"],
    ["偷别人了", "tōu bié rén le", "steal from others", "curi orang lain"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["让她", "ràng tā", "by her", "dengan itu"],
    ["这么一说", "zhè me yī shuō", "after she said that", "selepas dia berkata begitu"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["有些", "yǒu xiē", "somewhat", "agak"],
    ["脸红", "liǎn hóng", "blushed", "merah muka"],
    ["，", "", "", ""],
    ["周围", "zhōu wéi", "around", "sekeliling"],
    ["的", "de", "", ""],
    ["人", "rén", "people", "orang"],
    ["都", "dōu", "all", "semua"],
    ["看着", "kàn zhe", "looked at", "melihat"],
    ["我", "wǒ", "me", "saya"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["心里", "xīn lǐ", "in my heart", "dalam hati"],
    ["有些", "yǒu xiē", "somewhat", "agak"],
    ["别扭", "biè niu", "uncomfortable", "tidak selesa"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "lalu"],
    ["冲着", "chòng zhe", "facing", "menghadap"],
    ["她", "tā", "her", "dia"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["大声", "dà shēng", "loudly", "dengan kuat"],
    ["嚷什么", "rǎng shén me", "shouting what", "jerit apa"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段

    ["“", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["就是", "jiù shì", "just", "sahaja"],
    ["要", "yào", "want to", "hendak"],
    ["大声嚷", "dà shēng rǎng", "shout loudly", "jerit kuat"],
    ["，", "", "", ""],
    ["好让", "hǎo ràng", "to let", "supaya"],
    ["坏人", "huài rén", "bad people", "orang jahat"],
    ["怕我们", "pà wǒ men", "fear us", "takut kepada kita"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["那么小声", "nà me xiǎo shēng", "so quiet", "begitu perlahan"],
    ["，", "", "", ""],
    ["好像", "hǎo xiàng", "as if", "seolah-olah"],
    ["我们", "wǒ men", "we", "kita"],
    ["是", "shì", "are", "ialah"],
    ["坏人似的", "huài rén shì de", "bad people", "orang jahat"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["望着", "wàng zhe", "looking at", "memandang"],
    ["才", "cái", "only", "baru"],
    ["8岁", "bā suì", "eight-year-old", "lapan tahun"],
    ["的", "de", "", ""],
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["哑口无言", "yǎ kǒu wú yán", "speechless", "terdiam"],
    ["。", "", "", ""],
    ["想了一会儿", "xiǎng le yī huì r", "thought for a while", "berfikir sejenak"],
    ["，", "", "", ""],
    ["只好", "zhǐ hǎo", "had no choice but to", "terpaksa"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["算了", "suàn le", "Forget it", "Sudahlah"],
    ["，", "", "", ""],
    ["算了", "suàn le", "Forget it", "Sudahlah"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["买了", "mǎi le", "buy", "beli"],
    ["书", "shū", "books", "buku"],
    ["走吧", "zǒu ba", "let's go", "pergi"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["刚", "gāng", "just", "baru"],
    ["要", "yào", "was about to", "hendak"],
    ["掏钱", "tāo qián", "take out money", "mengeluarkan wang"],
    ["，", "", "", ""],
    ["想不到", "xiǎng bú dào", "unexpectedly", "tidak disangka"],
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["拦住", "lán zhù", "stopped", "menghalang"],
    ["我", "wǒ", "me", "saya"],
    ["，", "", "", ""],
    ["又", "yòu", "again", "lagi"],
    ["冲", "chòng", "facing", "menghadap"],
    ["那", "nà", "that", "itu"],
    ["卖书的人", "mài shū de rén", "bookseller", "penjual buku"],
    ["大声说", "dà shēng shuō", "said loudly", "berkata dengan kuat"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["看见", "kàn jiàn", "saw", "nampak"],
    ["你", "nǐ", "you", "awak"],
    ["刚才", "gāng cái", "just now", "tadi"],
    ["用", "yòng", "with", "dengan"],
    ["那样", "nà yàng", "that kind of", "begitu"],
    ["的眼光", "de yǎn guāng", "look", "pandangan"],
    ["看", "kàn", "look at", "melihat"],
    ["我妈妈", "wǒ mā ma", "my mom", "ibu saya"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["肯定", "kěn dìng", "must have", "pasti"],
    ["是", "shì", "was", "ialah"],
    ["看见", "kàn jiàn", "saw", "nampak"],
    ["小偷", "xiǎo tōu", "the thief", "pencuri"],
    ["掏", "tāo", "steal from", "curi dari"],
    ["我妈妈的兜", "wǒ mā ma de dōu", "my mom's pocket", "poket ibu saya"],
    ["，", "", "", ""],
    ["可", "kě", "but", "tetapi"],
    ["你", "nǐ", "you", "awak"],
    ["为什么", "wèi shén me", "why", "kenapa"],
    ["不说", "bù shuō", "didn't say", "tidak berkata"],
    ["？", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["帮助坏人", "bāng zhù huài rén", "help bad people", "membantu orang jahat"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["不买", "bù mǎi", "won't buy", "tidak beli"],
    ["你的书了", "nǐ de shū le", "your books", "buku awak"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["说完", "shuō wán", "after saying", "selepas berkata"],
    ["，", "", "", ""],
    ["拉着", "lā zhe", "pulled", "tarik"],
    ["我", "wǒ", "me", "saya"],
    ["就走", "jiù zǒu", "and left", "terus pergi"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["这才", "zhè cái", "only then", "baru"],
    ["想起来", "xiǎng qǐ lái", "remembered", "teringat"],
    ["，", "", "", ""],
    ["刚才", "gāng cái", "just now", "tadi"],
    ["小偷", "xiǎo tōu", "the thief", "pencuri"],
    ["在", "zài", "was", "di"],
    ["我旁边", "wǒ páng biān", "beside me", "di sisi saya"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["和", "hé", "and", "dan"],
    ["小偷", "xiǎo tōu", "the thief", "pencuri"],
    ["正对着", "zhèng duì zhe", "facing", "berhadapan dengan"],
    ["书摊", "shū tān", "bookstall", "gerai buku"],
    ["，", "", "", ""],
    ["卖书人", "mài shū rén", "the bookseller", "penjual buku"],
    ["看着", "kàn zhe", "watched", "melihat"],
    ["我", "wǒ", "me", "saya"],
    ["往", "wǎng", "into", "ke"],
    ["兜里", "dōu lǐ", "pocket", "poket"],
    ["掏钱", "tāo qián", "take out money", "mengeluarkan wang"],
    ["，", "", "", ""],
    ["一定", "yí dìng", "must have", "pasti"],
    ["也", "yě", "also", "juga"],
    ["看见了", "kàn jiàn le", "saw", "nampak"],
    ["小偷", "xiǎo tōu", "the thief", "pencuri"],
    ["正在", "zhèng zài", "was", "sedang"],
    ["掏", "tāo", "steal from", "curi dari"],
    ["我的钱", "wǒ de qián", "my money", "wang saya"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["不满地", "bù mǎn de", "discontentedly", "dengan tidak puas hati"],
    ["看着", "kàn zhe", "looked at", "melihat"],
    ["他", "tā", "him", "dia"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["看了", "kàn le", "looked at", "melihat"],
    ["我一眼", "wǒ yì yǎn", "me once", "saya"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["把", "bǎ", "to", "untuk"],
    ["头", "tóu", "head", "kepala"],
    ["扭到", "niǔ dào", "turned to", "pusing ke"],
    ["一边去", "yì biān qù", "one side", "satu sisi"],
    ["，", "", "", ""],
    ["什么", "shén me", "nothing", "tiada"],
    ["也没说", "yě méi shuō", "didn't say", "tidak berkata"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["牵起", "qiān qǐ", "took", "pegang"],
    ["女儿", "nǚ ér", "daughter's", "anak perempuan"],
    ["的手", "de shǒu", "hand", "tangan"],
    ["，", "", "", ""],
    ["生气地", "shēng qì de", "angrily", "dengan marah"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["走", "zǒu", "Let's go", "Pergi"],
    ["，", "", "", ""],
    ["我们不买了", "wǒ men bù mǎi le", "we won't buy", "kita tak beli"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 10 段

    ["我", "wǒ", "I", "Saya"],
    ["领着", "lǐng zhe", "led", "membawa"],
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["上了", "shàng le", "got on", "naik"],
    ["公共汽车", "gōng gòng qì chē", "bus", "bas"],
    ["，", "", "", ""],
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["瞪着一双", "dèng zhe yì shuāng", "opened wide", "membulatkan"],
    ["眼睛", "yǎn jīng", "eyes", "mata"],
    ["，", "", "", ""],
    ["东瞧瞧", "dōng qiáo qiao", "looking here", "lihat sana"],
    ["，", "", "", ""],
    ["西望望", "xī wàng wang", "looking there", "lihat sini"],
    ["，", "", "", ""],
    ["好像", "hǎo xiàng", "as if", "seolah-olah"],
    ["在找", "zài zhǎo", "looking for", "mencari"],
    ["什么", "shén me", "something", "apa-apa"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["拉了", "lā le", "pulled", "tarik"],
    ["她一下", "tā yí xià", "her once", "dia"],
    ["，", "", "", ""],
    ["小声问", "xiǎo shēng wèn", "asked quietly", "bertanya perlahan"],
    ["她", "tā", "her", "dia"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["干什么", "gàn shén me", "what are you doing", "buat apa"],
    ["呢", "ne", "particle", "?"],
    ["？”", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["看", "kàn", "see", "lihat"],
    ["有没有", "yǒu méi yǒu", "whether there is", "ada tak"],
    ["小偷", "xiǎo tōu", "a thief", "pencuri"],
    ["？”", "", "", ""],
    ["她又", "tā yòu", "she again", "dia lagi"],
    ["大声嚷", "dà shēng rǎng", "shouted loudly", "jerit kuat"],
    ["，", "", "", ""],
    ["声音", "shēng yīn", "voice", "suara"],
    ["宏亮", "hóng liàng", "loud", "kuat"],
    ["，", "", "", ""],
    ["传遍", "chuán biàn", "spread throughout", "bergema di"],
    ["整个", "zhěng gè", "the whole", "seluruh"],
    ["车厢", "chē xiāng", "bus carriage", "gerabak bas"],
    ["。", "", "", ""],
    ["周围", "zhōu wéi", "around", "Sekeliling"],
    ["的", "de", "", ""],
    ["人", "rén", "people", "orang"],
    ["愣了一下", "lèng le yí xià", "were stunned", "terkejut"],
    ["，", "", "", ""],
    ["接着", "jiē zhe", "then", "kemudian"],
    ["哄笑起来", "hōng xiào qǐ lái", "burst into laughter", "ketawa"],
    ["。", "", "", ""],
    ["旁边", "páng biān", "Beside", "Di sisi"],
    ["一个", "yí gè", "a", "seorang"],
    ["小伙子", "xiǎo huǒ zi", "young man", "pemuda"],
    ["逗她", "dòu tā", "teased her", "mengusiknya"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["就", "jiù", "With", "Dengan"],
    ["你这嗓门", "nǐ zhè sǎng mén", "your voice", "suara awak"],
    ["，", "", "", ""],
    ["有", "yǒu", "if there is", "ada"],
    ["小偷", "xiǎo tōu", "a thief", "pencuri"],
    ["也", "yě", "also", "juga"],
    ["早", "zǎo", "early", "sudah"],
    ["被你", "bèi nǐ", "by you", "oleh awak"],
    ["吓跑了", "xià pǎo le", "scared away", "takut lari"],
    ["！”", "", "", ""],
    ["另一位", "lìng yī wèi", "Another", "Seorang lagi"],
    ["中年妇女", "zhōng nián fù nǚ", "middle-aged woman", "wanita pertengahan umur"],
    ["好心地说", "hǎo xīn de shuō", "kindly said", "berkata dengan baik"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["要是", "yào shì", "If", "Kalau"],
    ["你真的", "nǐ zhēn de", "you really", "awak benar-benar"],
    ["看见", "kàn jiàn", "see", "nampak"],
    ["小偷", "xiǎo tōu", "a thief", "pencuri"],
    ["，", "", "", ""],
    ["千万别", "qiān wàn bié", "definitely don't", "jangan sekali-kali"],
    ["这么喊", "zhè me hǎn", "shout like this", "jerit begini"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["会", "huì", "will", "akan"],
    ["打", "dǎ", "hit", "pukul"],
    ["你的", "nǐ de", "you", "awak"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["女儿", "nǚ ér", "Daughter", "Anak perempuan"],
    ["扬起脸", "yáng qǐ liǎn", "raised her face", "menegakkan muka"],
    ["，", "", "", ""],
    ["冲着", "chòng zhe", "facing", "menghadap"],
    ["他们", "tā men", "them", "mereka"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["就是", "jiù shì", "just", "sahaja"],
    ["要", "yào", "want to", "hendak"],
    ["大声嚷", "dà shēng rǎng", "shout loudly", "jerit kuat"],
    ["，", "", "", ""],
    ["让", "ràng", "let", "supaya"],
    ["那些", "nà xiē", "those", "mereka"],
    ["坏人", "huài rén", "bad people", "orang jahat"],
    ["怕我们", "pà wǒ men", "fear us", "takut kepada kita"],
    ["，", "", "", ""],
    ["让", "ràng", "let", "supaya"],
    ["他们", "tā men", "them", "mereka"],
    ["不敢", "bù gǎn", "dare not", "tidak berani"],
    ["再做坏事", "zài zuò huài shì", "do bad things again", "buat jahat lagi"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段

    ["我", "wǒ", "I", "Saya"],
    ["张了张嘴", "zhāng le zhāng zuǐ", "opened my mouth", "buka mulut"],
    ["想说她", "xiǎng shuō tā", "wanted to say something", "hendak menegurnya"],
    ["，", "", "", ""],
    ["却", "què", "but", "tetapi"],
    ["没有", "méi yǒu", "didn't", "tidak"],
    ["说出口", "shuō chū kǒu", "say it", "berkata"],
    ["。", "", "", ""],
    ["周围", "zhōu wéi", "around", "Sekeliling"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["变得", "biàn de", "became", "menjadi"],
    ["安静", "ān jìng", "quiet", "senyap"],
    ["起来", "qǐ lái", "", ""],
    ["，", "", "", ""],
    ["人们", "rén men", "people", "orang ramai"],
    ["都", "dōu", "all", "semua"],
    ["闭紧嘴巴", "bì jǐn zuǐ ba", "closed their mouths", "tutup mulut"],
    ["不再说话", "bú zài shuō huà", "no longer spoke", "berhenti bercakap"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["车停了", "chē tíng le", "The bus stopped", "Bas berhenti"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["领着", "lǐng zhe", "led", "membawa"],
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["下了车", "xià le chē", "got off", "turun bas"],
    ["，", "", "", ""],
    ["走了两步", "zǒu le liǎng bù", "walked two steps", "berjalan dua langkah"],
    ["才想起来", "cái xiǎng qǐ lái", "only then remembered", "baru teringat"],
    ["忘了", "wàng le", "forgot", "lupa"],
    ["给女儿", "gěi nǚ ér", "to buy for daughter", "belikan anak"],
    ["买票", "mǎi piào", "buy ticket", "beli tiket"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["回过身来", "huí guò shēn lái", "turned around", "berpusing balik"],
    ["看见", "kàn jiàn", "saw", "melihat"],
    ["那个", "nà ge", "that", "itu"],
    ["平时", "píng shí", "usually", "biasa"],
    ["总是", "zǒng shì", "always", "selalu"],
    ["凶猛地", "xiōng měng de", "fiercely", "dengan garang"],
    ["盯着", "dīng zhe", "staring at", "merenung"],
    ["小孩", "xiǎo hái", "children", "kanak-kanak"],
    ["查票的", "chá piào de", "ticket inspector", "pemeriksa tiket"],
    ["女售票员", "nǚ shòu piào yuán", "female conductor", "konduktor wanita"],
    ["冲", "chòng", "towards", "ke arah"],
    ["我们", "wǒ men", "us", "kita"],
    ["友好地", "yǒu hǎo de", "friendly", "secara mesra"],
    ["笑了", "xiào le", "smiled", "tersenyum"],
    ["，", "", "", ""],
    ["车", "chē", "the bus", "bas"],
    ["就", "jiù", "then", "lalu"],
    ["开走了", "kāi zǒu le", "drove away", "berlalu"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 12 段

    ["这时候", "zhè shí hòu", "At this moment", "Pada masa ini"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["就想", "jiù xiǎng", "thought", "berfikir"],
    ["：", "", "", ""],
    ["也许", "yě xǔ", "perhaps", "mungkin"],
    ["我们", "wǒ men", "we", "kita"],
    ["大人的话", "dà rén de huà", "adults' words", "kata-kata orang dewasa"],
    ["，", "", "", ""],
    ["不一定", "bù yí dìng", "may not", "tidak semestinya"],
    ["就是对的", "jiù shì duì de", "be right", "betul"],
    ["，", "", "", ""],
    ["至少", "zhì shǎo", "at least", "sekurang-kurangnya"],
    ["我们", "wǒ men", "we", "kita"],
    ["在", "zài", "in", "dalam"],
    ["使用", "shǐ yòng", "using", "menggunakan"],
    ["声音", "shēng yīn", "voice", "suara"],
    ["这个问题上", "zhè ge wèn tí shàng", "this matter", "hal ini"],
    ["，", "", "", ""],
    ["就", "jiù", "just", "sahaja"],
    ["不如", "bù rú", "not as good as", "tidak sebaik"],
    ["小孩子", "xiǎo hái zi", "children", "kanak-kanak"],
    ["：", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["对自己的孩子", "duì zì jǐ de hái zi", "to our own children", "kepada anak sendiri"],
    ["使劲地嚷", "shǐ jìn de rǎng", "shout loudly", "jerit kuat"],
    ["，", "", "", ""],
    ["我们对父母", "wǒ men duì fù mǔ", "to parents", "kepada ibu bapa"],
    ["也曾", "yě céng", "also once", "pernah"],
    ["大过嗓门", "dà guò sǎng mén", "raise our voices", "naikkan suara"],
    ["，", "", "", ""],
    ["我们对朋友、同事", "wǒ men duì péng you tóng shì", "to friends and colleagues", "kepada kawan dan rakan sekerja"],
    ["也曾", "yě céng", "also once", "pernah"],
    ["高声叫喊", "gāo shēng jiào hǎn", "shout loudly", "jerit"],
    ["。", "", "", ""],
    ["唯独", "wéi dú", "only", "hanya"],
    ["面对", "miàn duì", "facing", "menghadapi"],
    ["危害", "wēi hài", "harming", "membahayakan"],
    ["我们的", "wǒ men de", "us", "kita"],
    ["坏人", "huài rén", "bad people", "orang jahat"],
    ["，", "", "", ""],
    ["却能", "què néng", "can", "boleh"],
    ["保持", "bǎo chí", "keep", "kekalkan"],
    ["沉默", "chén mò", "silent", "diam"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["林夕", "lín xī", "Lin Xi", "Lin Xi"],
    ["《", "", "", ""],
    ["大声地生活", "dà shēng de shēng huó", "Live Loudly", "Hidup Dengan Kuat"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
